version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/v2/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/v2/backend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
