name: CI
on:
  push: {}
  pull_request:
    branches:
      - "master"

jobs:
  lint:
    name: "Lint (${{ matrix.component }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, v2/frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.component }}
      - name: Build
        run: npm run lint
        working-directory: ${{ matrix.component }}
  build:
    name: "Build (${{ matrix.component }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, /v2/backend, v2/frontend]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.component }}
      - name: Build
        run: npm run build
        working-directory: ${{ matrix.component }}
