name: CI
on:
  push: {}

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  lint:
    name: "Lint (${{ matrix.component }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
        include:
          - component: frontend
            command: npm ci
          - component: backend
            command: npm ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: ${{ matrix.command }}
        working-directory: ${{ matrix.component }}
      - name: Lint
        run: npm run lint
        working-directory: ${{ matrix.component }}
  build:
    name: "Build (${{ matrix.component }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component: [frontend, backend]
        include:
          - component: frontend
            command: npm ci
          - component: backend
            command: npm ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: ${{ matrix.command }}
        working-directory: ${{ matrix.component }}
      - name: Create staging .env file
        if: ${{ env.BRANCH_NAME == 'dev' && matrix.component == 'frontend' }}
        run: echo "NEXT_PUBLIC_STAGING=true" >> .env
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: ${{ matrix.component }}
