name: Docker
on:
  push:
    branches:
      - "master"
      - "dev"

env:
  BUILD_TYPE: ${{ github.ref_name == 'refs/heads/dev' && 'staging' || 'prod' }}

jobs:
  build:
    name: "Build (${{ matrix.name }})"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        context: [backend, frontend]
        include:
          - context: backend
            name: backend
            file:
              prod: backend/Dockerfile
              staging: backend/Dockerfile
          - context: frontend
            name: frontend
            file:
              prod: frontend/production.dockerfile
              staging: frontend/staging.dockerfile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: ${{ matrix.file[env.BUILD_TYPE] }}
          tags: |
            ghcr.io/csesoc/freerooms-${{ matrix.name }}:${{ github.sha }}
            ghcr.io/csesoc/freerooms-${{ matrix.name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    name: Deploy (CD)
    runs-on: ubuntu-latest
    needs: [build]
    concurrency: staging
    if: ${{ github.event_name != 'pull_request' && (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master')  }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: csesoc/deployment
          token: ${{ secrets.GH_TOKEN }}
      - name: Install yq - portable yaml processor
        uses: mikefarah/yq@v4.34.2
      - name: Update deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "CSESoc CD"
          git config user.email "technical@csesoc.org.au"

          git checkout -b update/freerooms-$BUILD_TYPE/${{ github.sha }}
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/freerooms-backend:${{ github.sha }}"' apps/projects/freerooms/$BUILD_TYPE/deploy-backend.yml
          yq -i '.items[0].spec.template.spec.containers[0].image = "ghcr.io/csesoc/freerooms-frontend:${{ github.sha }}"' apps/projects/freerooms/$BUILD_TYPE/deploy-frontend.yml

          git add . 
          git commit -m "feat(freerooms-$BUILD_TYPE): update images" 
          git push -u origin update/freerooms-$BUILD_TYPE/${{ github.sha }}
          gh pr create --title "feat(freerooms-$BUILD_TYPE): update image" --body "Updates the image for the freerooms deployment to commit csesoc/Freerooms@${{ github.sha }}." > URL
          gh pr merge $(cat URL) --squash -d
