name: Docker
on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build (${{ matrix.name }})"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        context: [frontend, v2/backend, v2/frontend]
        includes:
          - context: frontend
            name: vue
          - context: v2/backend
            name: backend
          - context: v2/frontend
            name: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: client
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64
          file: ${{ matrix.context }}/Dockerfile
          tags: |
            ghcr.io/csesoc/freerooms-${{ matrix.name }}:${{ github.sha }}
            ghcr.io/csesoc/freerooms-${{ matrix.name }}:latest
          labels: ${{ steps.meta.outputs.labels }}
